# Generated by Django 3.0.2 on 2020-01-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drivers_Selection', '0003_auto_20200119_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='fuel_consumption',
            field=models.CharField(default='', max_length=50),
        ),
    ]
