# Generated by Django 3.0.2 on 2020-01-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drivers_Selection', '0004_driver_fuel_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='available_seats',
            field=models.CharField(default='', max_length=50),
        ),
    ]
