# Generated by Django 3.0.2 on 2020-01-22 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Drivers_Selection', '0005_driver_available_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='destination_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_place', to='Drivers_Selection.Place'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='starting_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='starting_place', to='Drivers_Selection.Place'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='available_seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='driver',
            name='fuel_consumption',
            field=models.FloatField(),
        ),
    ]
