# Generated by Django 3.0.2 on 2020-01-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drivers_Selection', '0005_driver_available_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='available_seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='driver',
            name='fuel_consumption',
            field=models.FloatField(),
        ),
    ]
