# Generated by Django 3.0.2 on 2020-01-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drivers_Selection', '0006_auto_20200122_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='vaffanculo',
            field=models.CharField(default='', max_length=20),
        ),
    ]
