# Generated by Django 3.0.2 on 2020-01-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drivers_Selection', '0006_auto_20200121_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='destination_place',
            field=models.ManyToManyField(related_name='destination_place', to='Drivers_Selection.Place'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='starting_place',
            field=models.ManyToManyField(related_name='starting_place', to='Drivers_Selection.Place'),
        ),
    ]
