# Generated by Django 3.0.2 on 2020-01-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drivers_Selection', '0007_place_vaffanculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='vaffanculo',
        ),
    ]
