# Generated by Django 3.0.2 on 2020-01-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drivers_Selection', '0008_remove_place_vaffanculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_destination',
            field=models.BooleanField(default=True),
        ),
    ]
