# Generated by Django 3.0.2 on 2020-01-21 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drivers_Selection', '0008_auto_20200121_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='destination_place',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='starting_place',
        ),
    ]
