# Generated by Django 3.0.2 on 2020-01-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drivers_Selection', '0009_place_is_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='string_coordinates',
            field=models.CharField(default='', max_length=200),
        ),
    ]
