# Generated by Django 3.0.2 on 2020-01-22 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drivers_Selection', '0010_place_string_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='string_coordinates',
        ),
    ]
