# Generated by Django 3.0.2 on 2020-01-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drivers_Selection', '0011_remove_place_string_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
