# Generated by Django 3.0.2 on 2020-01-23 10:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drivers_Selection', '0014_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='elements',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), size=None),
        ),
    ]
