# Generated by Django 3.0.2 on 2020-01-23 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Drivers_Selection', '0016_auto_20200123_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankelement',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Drivers_Selection.Rank'),
        ),
    ]
