# Generated by Django 3.0.2 on 2020-01-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drivers_Selection', '0020_remove_passenger_destination_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankelement',
            name='last_name_element',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='country_code',
            field=models.CharField(default='IT', max_length=2),
        ),
    ]
