# Generated by Django 3.0.2 on 2020-01-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drivers_Selection', '0021_auto_20200124_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='country_code',
            field=models.CharField(default='IT', max_length=2),
        ),
    ]
